image: mono:latest

stages:
    - test
    - build

cache:
  paths:
  - .veronique/

release:
    stage: build
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - LinkTime.exe
          - LICENSE.md
          - CHANGELOG.md
          - AUTHORS.txt
    script:
        - ./Build.sh --configuration=Release
        - cp Build/Release/LinkTime.exe LinkTime.exe

ci-release:
    stage: build
    only:
        - master
    except:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_SHA}"
        expire_in: 4 weeks
        paths:
          - LinkTime.exe
          - LICENSE.md
          - CHANGELOG.md
          - AUTHORS.txt
    script:
        - ./Build.sh --configuration=Release
        - cp Build/Release/LinkTime.exe LinkTime.exe
    
ci-debug:
    stage: test
    script:
        - apt-get -qq update
        - apt-get -yqq install tree
        - ./Build.sh || true
        - tree -a ./