image: mono:latest

stages:
    - test
    - build

before_script:
    - apt-get -qq update
    - apt-get -yqq install libcurl3

cache:
  paths:
  - .cache/

release:
    stage: build
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.zip
    script:
        - ./build.sh --configuration=Release

ci-release:
    stage: build
    only:
        - master
    except:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_SHA}"
        expire_in: 4 weeks
        paths:
          - ./*.zip
    script:
        - ./build.sh --configuration=Release
    
ci-debug:
    stage: test
    script:
        - ./build.sh